eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER}


server:
  port: ${SERVER_PORT:8080}

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${AUTH_SERVER:http://localhost:8082}
