DB_URL: jdbc:mysql://192.168.244.133:3306/vmall_user
DB_USERNAME: root
DB_PASSWORD: root
SERVER_PORT: 8082

RABBIT_MQ_HOST: 192.168.244.133
RABBIT_MQ_PORT: 5672
RABBIT_MQ_USER: guest
RABBIT_MQ_PASSWORD: guest
RABBIT_MQ_VIRTUAL_HOST: /

QUEUE_SEND_NOTIFICATION_QUEUE_NAME: local.send.notification.queue
QUEUE_SEND_NOTIFICATION_EXCHANGE: local.send.notification.exchange
QUEUE_SEND_NOTIFICATION_ROUTING_KEY: local.send.notification.routing-key

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:temp_data.sql